### ISSUE TITLE
Styling Edits To-do's

### ISSUE THREAD

**Issue by rudyjm3** [rudyjm3/tool-rental-maint-log#5]
### Capitalization
- [x] Capitalize 1st word of inputs. 
-  [x] Capitalize each word for the equipment description

### Sizing and style
- [x] Set max widths (desktop) for header columns: Equipment description, Service description, hour meter, and tech name.
- [x] Fix form open / close animation with from to keyframe in css.
